name: Test
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tess
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.0'
      - run: npm install
      - name: Run tests
      - run: npm test
